name: Auto PR to Main

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: develop
          base: main
          title: "Auto PR: Merge `develop` into `main`"
          body: "This PR was automatically created by GitHub Actions."
          labels: "auto-pr"
          draft: false
